### ISSUE TITLE
Issue when building with catgo

### ISSUE THREAD

**Issue by IDKLOLSS** [saltysimulations/saltyreplay#1]
error: failed to run custom build command for `msfs v0.0.1-alpha.2`

Caused by:
  process didn't exit successfully: `C:\Users\blake\Downloads\saltyreplay-master\target\debug\build\msfs-afc3fdf5367ff567\build-script-build` (exit code: 101)
  --- stdout
  Found MSFS SDK: "C:\\MSFS SDK\\"
  cargo:rerun-if-changed=src/bindgen_support/wrapper.h

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.55.1\src/lib.rs:1896:31
  stack backtrace:
     0:     0x7ff6ce97b7d5 - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff6ce97b7d5 - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff6ce97b7d5 - std::sys_common::backtrace::_print_fmt
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sys_common\backtrace.rs:67
     3:     0x7ff6ce97b7d5 - std::sys_common::backtrace::_print::{{impl}}::fmt
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sys_common\backtrace.rs:46
     4:     0x7ff6ce999cbb - core::fmt::write
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\core\src\fmt\mod.rs:1078
     5:     0x7ff6ce975d7d - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\io\mod.rs:1519
     6:     0x7ff6ce97ed1d - std::sys_common::backtrace::_print
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sys_common\backtrace.rs:49
     7:     0x7ff6ce97ed1d - std::sys_common::backtrace::print
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sys_common\backtrace.rs:36
     8:     0x7ff6ce97ed1d - std::panicking::default_hook::{{closure}}
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:208
     9:     0x7ff6ce97e82a - std::panicking::default_hook
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:225
    10:     0x7ff6ce97f65e - std::panicking::rust_panic_with_hook
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:591
    11:     0x7ff6ce97f181 - std::panicking::begin_panic_handler::{{closure}}
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:497
    12:     0x7ff6ce97c1af - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sys_common\backtrace.rs:141
    13:     0x7ff6ce97f0d9 - std::panicking::begin_panic_handler
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:493
    14:     0x7ff6ce998240 - core::panicking::panic_fmt
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\core\src\panicking.rs:92
    15:     0x7ff6ce998063 - core::option::expect_none_failed
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\core\src\option.rs:1268
    16:     0x7ff6ce4634bb - core::result::Result<tuple<>, alloc::string::String>::expect<tuple<>,alloc::string::String>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:933
    17:     0x7ff6ce3aab2c - core::ops::function::FnOnce::call_once<fn() -> alloc::sync::Arc<clang_sys::SharedLibrary>,tuple<>>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
    18:     0x7ff6ce4f24e6 - lazy_static::lazy::{{impl}}::get::{{closure}}<alloc::sync::Arc<clang_sys::SharedLibrary>,fn() -> alloc::sync::Arc<clang_sys::SharedLibrary>>
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\inline_lazy.rs:31
    19:     0x7ff6ce3d561e - std::sync::once::{{impl}}::call_once::{{closure}}<closure-0>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sync\once.rs:261
    20:     0x7ff6ce97ae51 - std::sync::once::Once::call_inner
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\sync\once.rs:420
    21:     0x7ff6ce3d5427 - std::sync::once::Once::call_once<closure-0>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sync\once.rs:261
    22:     0x7ff6ce3a88c5 - lazy_static::lazy::Lazy<alloc::sync::Arc<clang_sys::SharedLibrary>>::get
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\inline_lazy.rs:30
    23:     0x7ff6ce3a88c5 - bindgen::ensure_libclang_is_loaded::{{impl}}::deref::__stability
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\lib.rs:142
    24:     0x7ff6ce3a88c5 - bindgen::ensure_libclang_is_loaded::{{impl}}::deref
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\lib.rs:144
    25:     0x7ff6ce39fd46 - bindgen::ensure_libclang_is_loaded
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.55.1\src\lib.rs:1904
    26:     0x7ff6ce3a02ca - bindgen::Bindings::generate
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.55.1\src\lib.rs:1962
    27:     0x7ff6ce39e326 - bindgen::Builder::generate
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.55.1\src\lib.rs:1335
    28:     0x7ff6ce3919b4 - build_script_build::main
                                 at C:\Users\blake\.cargo\registry\src\github.com-1ecc6299db9ec823\msfs-0.0.1-alpha.2\build.rs:43
    29:     0x7ff6ce3925ab - core::ops::function::FnOnce::call_once<fn(),tuple<>>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
    30:     0x7ff6ce392cdb - std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:125
    31:     0x7ff6ce392b51 - std::rt::lang_start::{{closure}}<tuple<>>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
    32:     0x7ff6ce97f954 - core::ops::function::impls::{{impl}}::call_once
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\library\core\src\ops\function.rs:280
    33:     0x7ff6ce97f954 - std::panicking::try::do_call
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:379
    34:     0x7ff6ce97f954 - std::panicking::try
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panicking.rs:343
    35:     0x7ff6ce97f954 - std::panic::catch_unwind
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\panic.rs:396
    36:     0x7ff6ce97f954 - std::rt::lang_start_internal
                                 at /rustc/ff59982926d98c8508008f0559f8a055260ac05e\/library\std\src\rt.rs:51
    37:     0x7ff6ce392b23 - std::rt::lang_start<tuple<>>
                                 at C:\Users\blake\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
    38:     0x7ff6ce391ed0 - main
    39:     0x7ff6ce9a14c4 - invoke_main
                                 at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    40:     0x7ff6ce9a14c4 - __scrt_common_main_seh
                                 at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    41:     0x7ff857577034 - BaseThreadInitThunk
    42:     0x7ff857a5d0d1 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ninjomcs** [comment]
Resolved in Discord, for anyone else make sure clang is installed and that the MSFS SDK is installed to C:\MSFS SDK or that an environment variable is set up.
