### ISSUE TITLE
Fix The Readme Command

### ISSUE THREAD

**Issue by michaelmagdy15** [saltysimulations/saltyreplay#2]
Please Fix The Loopback Command In Your Read Me.

The correct one - > CheckNetIsolation LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"

**Comment by ninjomcs** [comment]
according to the tauri documentation the current one is correct: https://tauri.studio/en/docs/getting-started/setup-windows. did you have issues with the one in the readme?
